[build]
  command = "serverless package"
  publish = ".serverless"

[plugins]
  [plugins.serverless-python]
    package = "zip"
    include = ["netlify/functions", "requirements.txt"]  
    exclude = ["node_modules"]
    runtime = "python3.11.9"  
